# Generated by Django 3.0.7 on 2020-07-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200724_2002'),
        ('carts', '0005_auto_20200724_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='updateed_at',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, to='products.Product'),
        ),
    ]
