# Generated by Django 3.0.7 on 2020-07-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200724_2002'),
        ('carts', '0006_auto_20200726_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(to='products.Product'),
        ),
    ]
