# Generated by Django 3.0.7 on 2020-07-25 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image'),
        ('orders', '0004_auto_20200718_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='products.Product'),
        ),
    ]
